Aaditya Parajuli

4.1 Warm Up Exercise: Basic Vector and Matrix Operation with Numpy.

4.1 Initializing an empty array with size 2X2.




In [ ]:
import numpy as np

array_1=np.empty((2,2))
print(array_1)

[[2.8449169e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]


4.2 Initializing all one array with size 4X2.

In [ ]:
array_2=np.ones((4, 2))
print(array_2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**4.3** Returned a new array of given shape,type filled with fill value

In [ ]:
array_3=np.full((2,7),fill_value=15)
print(array_3)

[[15 15 15 15 15 15 15]
 [15 15 15 15 15 15 15]]


*4.4 Return a new array of zeros with same shape and type as a given array

In [ ]:
array_first=np.arange(1,5).reshape((2,2))
array_4=np.zeros_like(array_first)
print("---------------result--------------")
print(array_first)
print("")
print(array_4)

---------------result--------------
[[1 2]
 [3 4]]

[[0 0]
 [0 0]]


4.5 Return a new array of ones with same shape and type as given array.

In [ ]:
array_first1=np.arange(11,15).reshape((2,2))
array_5=np.ones_like(array_first1)
print("---------------result--------------")
print(array_first)
print("")
print(array_5)

---------------result--------------
[[1 2]
 [3 4]]

[[1 1]
 [1 1]]


4.6 For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [ ]:
new_list=[1,2,3,4]
array_6=np.array(new_list)
print(array_6)

[1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

1.Creating an array with values ranging from 10 to 49.

In [ ]:
array1=np.arange(10,50)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Creating a 3X3 matrix with values ranging from 0 to 8.

In [ ]:
array2=np.arange(0,9).reshape((3,3))
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Created a 3X3 identity matrix.

In [ ]:
array3=np.eye(3)
print(array3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.Create a random array of size 30 and find the mean of the array.

In [ ]:
array4=np.random.random(79)
mean_array=array4.mean()
print(mean_array)

0.49314716750087806


5.Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
array5=np.random.random((10, 10))
print(array5)
print(f"{array5.min()} is the minimum value in array")
print(f"{array5.max()} is the maximum value in array")

[[0.18037522 0.46255499 0.5610685  0.4529737  0.52559986 0.98284223
  0.23385062 0.8302794  0.14047996 0.04995601]
 [0.79572135 0.95408928 0.03438855 0.02912508 0.86964574 0.09581555
  0.7664588  0.36887504 0.86427651 0.0397528 ]
 [0.88184543 0.10669494 0.57191265 0.13767358 0.95595191 0.73024758
  0.34723501 0.02126229 0.53763064 0.45173204]
 [0.3754479  0.81625927 0.74831902 0.17505689 0.23598641 0.9706295
  0.25190875 0.56838272 0.31636064 0.88049415]
 [0.28323839 0.06414446 0.66282976 0.43530439 0.813112   0.57567168
  0.61015733 0.59267163 0.46012327 0.07733505]
 [0.28047106 0.25817585 0.87057504 0.60530086 0.3495636  0.49254022
  0.03998248 0.58544875 0.01087084 0.48150278]
 [0.37989112 0.09712051 0.8326497  0.95322444 0.43950202 0.91996788
  0.34976897 0.65455069 0.13866485 0.74775446]
 [0.85238264 0.53087309 0.50934935 0.82962652 0.07558109 0.4309187
  0.19012362 0.87327406 0.40915185 0.10504942]
 [0.91111269 0.23425318 0.31004665 0.60720777 0.67691752 0.35673431
  0.23639947 0

6.Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
array6=np.zeros(10)
print(array6)
print("")
array6[4]=1
print(array6)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.Reverse an array arr = [1,2,0,0,4,0]

In [ ]:
array7=np.array([1,2,0,0,4,0])
res_array=array7[::-1]
print(res_array)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
border_array = np.ones((4, 4))
border_array[1:-1, 1:-1] = 0
print("result = \n", border_array)

result = 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
array8=np.indices((8, 8)).sum(axis=0) % 2
print("result = \n",array8)

result = 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3.Array Operations:

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two array.
print("Add : \n",np.add(x,y))

#2. Subtract the two array.
print("subtract : \n",np.subtract(x,y))

# 3. Multiply the array with any integers of your choice.
print("multiply : \n",np.multiply(3,x))

# 4. Find the square of each element of the array.
print("square : \n",np.square(x))

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("dot product of v(and)w : ",np.dot(v,w))
print("dot product of x(and)v : \n",np.dot(x,v))
print("dot product of x(and)y : \n",np.dot(x,y))


# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_row=np.concatenate((x, y), axis=0)
concat_col=np.vstack((v, w)).T
print("Concatenate x(and)y along row : \n",concat_row)
print("Concatenate v(and)w along column : \n",concat_col)

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempt to concatenate along rows
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError during concatenation of x and v:", e)

# error because v and x didn't have matching dimensions
# Fixing the error by reshaping v to match x's dimensions
v_reshaped = v[np.newaxis, :]  # Reshape v to (1, 2)
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\nConcatenation of x and reshaped v:\n", concat_xv_fixed)



Add : 
 [[ 6  8]
 [10 13]]
subtract : 
 [[-4 -4]
 [-4 -3]]
multiply : 
 [[ 3  6]
 [ 9 15]]
square : 
 [[ 1  4]
 [ 9 25]]
dot product of v(and)w :  219
dot product of x(and)v : 
 [29 77]
dot product of x(and)y : 
 [[19 22]
 [50 58]]
Concatenate x(and)y along row : 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v(and)w along column : 
 [[ 9 11]
 [10 12]]

Error during concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Concatenation of x and reshaped v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


4.Matrix operations

4.1 prove:

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A.A−1 = I.
inverse_of_A=np.linalg.inv(A)
product=np.dot(A,inverse_of_A)
print("A.A−1 = I \n",product)


# 2. Prove AB ̸= BA.
product_of_A_B=np.dot(A,B)
product_of_B_A=np.dot(B,A)
print("A.B = \n",product_of_A_B)
print("B.A = \n",product_of_B_A)
check=np.array_equal(product_of_A_B,product_of_B_A)
print("A.B = B.A ? ->",check)

# 3. Prove (AB)ᵀ = Bᵀ . Aᵀ
AB_T=np.transpose(product_of_A_B)
B_T=np.transpose(B)
A_T=np.transpose(A)
product_of_BT_AT=np.dot(B_T,A_T)
print("(AB)ᵀ = \n",AB_T)
print(" Bᵀ. Aᵀ = \n",product_of_BT_AT)
check=np.array_equal(AB_T,product_of_BT_AT)
print("(AB)ᵀ = Bᵀ . Aᵀ ? ->",check)







A.A−1 = I 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
A.B = 
 [[23 13]
 [51 29]]
B.A = 
 [[36 44]
 [13 16]]
A.B = B.A ? -> False
(AB)ᵀ = 
 [[23 51]
 [13 29]]
 Bᵀ. Aᵀ = 
 [[23 51]
 [13 29]]
(AB)ᵀ = Bᵀ . Aᵀ ? -> True


4.2 Solve the following system of Linear equation using Inverse Methods.

In [ ]:
# Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))
if det_A != 0:
  cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])
  adjoint_A = cofactor_matrix.T
  inverse_of_A = adjoint_A / det_A
  print("Inverse of A:\n", inverse_of_A)
  X = np.dot(inverse_of_A,B)
  print("Solution = ",X)

else:
  print("No solution exists as the determinant of A is zero.")


Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution =  [ 2.  1. -2.]


In [ ]:
# Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
# solve the above equation using np.linalg.inv function
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

det_A=np.linalg.det(A)
# AX = B
# or,X= A⁻¹ * B
if det_A != 0:
    inverse_of_A = np.linalg.inv(A)
    X = np.dot(inverse_of_A, B)
    print("Solution = ",X)
else:
  print("No solution exists as the determinant of A is zero.")

Solution =  [ 2.  1. -2.]


4.2 Experiment : How Fast is Numpy

1. Element-wise Add

In [ ]:
import time

#Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
#and Print the time taken for this operation.
list1=[i for i in range(1000000)]
list2=[i for i in range(1000000)]
start_time=time.time()
result=[list1[i]+list2[i] for i in range(len(list1))]
end_time=time.time()
time_taken=end_time-start_time
print(f"time taken by python list = {time_taken} second")

#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
#operation.
array_1=np.array(list1)
array_2=np.array(list2)
start_time=time.time()
result=array_1+array_2
end_time=time.time()
time_taken=end_time-start_time
print(f"time taken by numpy array = {time_taken} second")

time taken by python list = 0.12944769859313965 second
time taken by numpy array = 0.007074117660522461 second


2. Element-wise Multiplication

In [ ]:
import time

#Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-sure and Print the time taken for this operation.
list1=[i for i in range(1000000)]
list2=[i for i in range(1000000)]
start_time=time.time()
result=[list1[i]*list2[i] for i in range(len(list1))]
end_time=time.time()
time_taken=end_time-start_time
print(f"time taken by python list = {time_taken} second")

#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
array_1=np.array(list1)
array_2=np.array(list2)
start_time=time.time()
result=array_1*array_2
end_time=time.time()
time_taken=end_time-start_time
print(f"time taken by numpy array = {time_taken} second")

time taken by python list = 0.1189417839050293 second
time taken by numpy array = 0.027172327041625977 second


3. Dot Product

In [ ]:
import time

#Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
list1=[i for i in range(1000000)]
list2=[i for i in range(1000000)]
start_time=time.time()
result=sum(list1[i] * list2[i] for i in range(len(list1)))
end_time=time.time()
time_taken=end_time-start_time
print(f"time taken by python list = {time_taken} second")

#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
array_1=np.array(list1)
array_2=np.array(list2)
start_time=time.time()
result=np.dot(array_1,array_2)
end_time=time.time()
time_taken=end_time-start_time
print(f"time taken by numpy array = {time_taken} second")

time taken by python list = 0.14185476303100586 second
time taken by numpy array = 0.002291440963745117 second


4. Matrix Multiplication

In [ ]:
import time

#Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
print("4. Matrix Multiplication")
size = 100


matrix_1 = [[i for i in range(size)] for _ in range(size)]
matrix_2 = [[j for j in range(size)] for _ in range(size)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix_2)] for row in matrix_1]
end_time = time.time()
time_taken = end_time - start_time
print(f"time taken by python list = {time_taken} second")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix_1)
matrix2_np = np.array(matrix_2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
time_taken = end_time - start_time
print(f"time taken by python list = {time_taken} second")

4. Matrix Multiplication
time taken by python list = 0.08334231376647949 second
time taken by python list = 0.0014276504516601562 second
